DROP TABLE IF EXISTS `breeding`;

DROP TABLE IF EXISTS `cat_group`;

DROP TABLE IF EXISTS `treatment`;

DROP TABLE IF EXISTS `treatment_type`;

DROP TABLE IF EXISTS `cat`;

DROP TABLE IF EXISTS `sessions`;

DROP TABLE IF EXISTS `users`;