version: "3.1"

services:
  database:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "database:/var/lib/mysql"
    secrets:
      - db_root_password
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - app
  
  backend:
    image: backend
    build: .
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      - db
    env_file:
      - .env

networks:
  app:
    driver: bridge

volumes:
  database:
    name: database
    driver: local

env_file:
  - path: ./.env
    required: true 

