version: "3.1"

services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    volumes:
      - "./.backup/database:/var/lib/mysql"
    networks:
      - app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 5001:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - app
  
  backend:
    container_name: backend
    image: backend
    build: .
    ports:
      - 5000:8080
    volumes:
      - "./.backup/uploads:/root/uploads"
      - "./others:/root/others"
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

networks:
  app:
    driver: bridge

