version: "3.1"

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./others/nginx:/etc/nginx/templates
    networks:
      - app

  db:
    container_name: db
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "./.data/database:/var/lib/mysql"
    networks:
      - app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - app
  
  backend:
    container_name: backend
    image: backend
    build: .
    ports:
      - 8080:8080
    volumes:
      - "./.data/uploads:/root/uploads"
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

networks:
  app:
    driver: bridge

