version: "3.1"

services:
  db:
    container_name: db
    image: mysql
    restart: on-failure
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Bangkok
    ports:
      - 3306:3306
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2

  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - 3307:8080
    environment:
      ADMINER_DESIGN: 'dracula'
    networks:
      - app
  
  backend:
    container_name: backend
    restart: on-failure
    image: backend
    build: .
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

networks:
  app:
    driver: bridge

volumes:
  database:
    name: database
    driver: local

