@url = 
@token = 

POST {{url}}/auth/login

{
    "username": "admin",
    "password": "admin"
}

###

POST {{url}}/auth/register
Content-Type: application/json

{
    "username": "test",
    "password": "test",
    "email": "test@gmail.com",
    "gender": "male",
    "date":"21/10/2000"
}

###

DELETE  {{url}}/auth/logout
Authorization: Bearer {{token}}
