@url = 
@token = 

POST {{url}}/auth/login

{
    "username": "",
    "password": ""
}

###

POST {{url}}/auth/register
Content-Type: application/json

{
    "username": "",
    "password": "",
    "email": "",
    "gender": "",
    "date":""
}

###

DELETE  {{url}}/auth/logout
Authorization: Bearer {{token}}
