@url = http://localhost:8080/api
@token = 


GET {{url}}/cat
Authorization: Bearer {{token}}

###

GET  {{url}}/cat/2
Authorization: Bearer {{token}}

###

post {{url}}/cat
Authorization: Bearer {{token}}

{
    "name": "Nana",
    "gender":"Female",
    "profile":"",
    "weight":10,
    "date":"2000-10-21"
}

###

put {{url}}/cat/1
Authorization: Bearer {{token}}

{
    "name": "Mori",
    "gender":"Male",
    "profile":"",
    "weight":12,
    "date":"2000-10-21"
}

###

delete {{url}}/cat/1
Authorization: Bearer {{token}}