@url = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5YjMxYjk2LTMxNTgtNDA0Yi04ZTcxLTk2MDViYjdjMGI2MCJ9.xafbfwB14QE_ha5O2cmQGGJNCKof1hS3oL_x2ZtLVe4


GET {{url}}/user
Authorization: Bearer {{token}}

###

put {{url}}/user
Authorization: Bearer {{token}}

{
    "username": "admin2",
    "email": "test@gmail2.com",
    "gender": "male",
    "date":"21/10/2000"
}

###

PUT {{url}}/user/password
Authorization: Bearer {{token}}

{
    "password": "admin2"
}