@url = 
@token = 


GET {{url}}/user
Authorization: Bearer {{token}}

###

put {{url}}/user
Authorization: Bearer {{token}}

{
    "username": "admin2",
    "email": "test@gmail2.com",
    "gender": "male",
    "date":"21/10/2000"
}

###

PUT {{url}}/user/password
Authorization: Bearer {{token}}

{
    "password": "admin2"
}